### ISSUE TITLE
max-answers tarvitaan myös exam-tasolle

### ISSUE THREAD

**Issue by eeroan** [digabi/koeformaatti#3]
Monissa kokeissa (esim. psykologia ja fysiikka) tarvitaan myös tieto siitä kuinka moneen tehtävään saa vastata kokeessa yhteensä. Pitäisikö tämäkin voidan jotenkin mallintaa?

**Comment by AleksiAhtiainen** [comment]
Tämä on lisätty, ks. https://github.com/digabi/koeformaatti/commit/a007da118fed66e42ba407702b6c49f560ee88f2
